### ISSUE TITLE
Danish lang file

### ISSUE THREAD

**Issue by Alexey-T** [scootergrisen/phpbb_da#1]
I see you've translated FeatherPad. can you pls, translate CudaText too? Thanks. 
http://wiki.freepascal.org/CudaText#How_to_make_translation

**Comment by scootergrisen** [comment]
I don't think i will i have never used it.
If you want to make it easier to translate you can use po/pot file.
Translating and updating the ini file is not easy.
Imagine you have a translation made 1 year ago and now you want to update it to the latest version. Not easy. With po/pot its much better and people might already know po/pot if they have translated other software.

**Comment by Alexey-T** [comment]
Declined...
